
import numpy as np
import pylab as plt


rmsG_m0_b1 = np.loadtxt("G_m0_b1.dat", float)
rmsG_m1_b1 = np.loadtxt("G_m1_b1.dat", float)
rmsG_m2_b1 = np.loadtxt("G_m2_b1.dat", float)
rmsG_m3_b1 = np.loadtxt("G_m3_b1.dat", float)
rmsG_m4_b1 = np.loadtxt("G_m4_b1.dat", float)

rmsG_m0_b2 = np.loadtxt("G_m0_b2.dat", float)
rmsG_m1_b2 = np.loadtxt("G_m1_b2.dat", float)
rmsG_m2_b2 = np.loadtxt("G_m2_b2.dat", float)
rmsG_m3_b2 = np.loadtxt("G_m3_b2.dat", float)
rmsG_m4_b2 = np.loadtxt("G_m4_b2.dat", float)

rmsG_m0_b4 = np.loadtxt("G_m0_b4.dat", float)
rmsG_m1_b4 = np.loadtxt("G_m1_b4.dat", float)
rmsG_m2_b4 = np.loadtxt("G_m2_b4.dat", float)
rmsG_m3_b4 = np.loadtxt("G_m3_b4.dat", float)
rmsG_m4_b4 = np.loadtxt("G_m4_b4.dat", float)


plt.plot(rmsG_m0_b1[:,0], rmsG_m0_b1[:,1], label='m=0')
plt.plot(rmsG_m1_b1[:,0], rmsG_m1_b1[:,1], label='m=1')
plt.plot(rmsG_m2_b1[:,0], rmsG_m2_b1[:,1], label='m=2')
plt.plot(rmsG_m3_b1[:,0], rmsG_m3_b1[:,1], label='m=3')
plt.plot(rmsG_m4_b1[:,0], rmsG_m4_b1[:,1], label='m=4')
plt.plot(loc='best')
plt.grid(True)
plt.xlim(0,2)
plt.legend(loc='best')
plt.xlabel(r"$W$", fontsize="15")
plt.ylabel(r"$rms(G)$", fontsize="15")
plt.title(r"$\beta=1$", fontsize='20')
plt.tick_params(axis='both', which='major', labelsize=12)
plt.show()

plt.plot(rmsG_m0_b2[:,0], rmsG_m0_b2[:,1], label='m=0')
plt.plot(rmsG_m1_b2[:,0], rmsG_m1_b2[:,1], label='m=1')
plt.plot(rmsG_m2_b2[:,0], rmsG_m2_b2[:,1], label='m=2')
plt.plot(rmsG_m3_b2[:,0], rmsG_m3_b2[:,1], label='m=3')
plt.plot(rmsG_m4_b2[:,0], rmsG_m4_b2[:,1], label='m=4')
plt.plot(loc='best')
plt.grid(True)
plt.legend(loc='best')
plt.xlabel(r"$W$", fontsize="15")
plt.ylabel(r"$rms(G)$", fontsize="15")
plt.title(r"$\beta=2$", fontsize='20')
plt.tick_params(axis='both', which='major', labelsize=12)
plt.show()

plt.plot(rmsG_m0_b4[:,0], rmsG_m0_b4[:,1], label='m=0')
plt.plot(rmsG_m1_b4[:,0], rmsG_m1_b4[:,1], label='m=1')
plt.plot(rmsG_m2_b4[:,0], rmsG_m2_b4[:,1], label='m=2')
plt.plot(rmsG_m3_b4[:,0], rmsG_m3_b4[:,1], label='m=3')
plt.plot(rmsG_m4_b4[:,0], rmsG_m4_b4[:,1], label='m=4')
plt.plot(loc='best')
plt.grid(True)
plt.legend(loc='best')
plt.xlabel(r"$W$", fontsize="15")
plt.ylabel(r"$rms(G)$", fontsize="15")
plt.title(r"$\beta=4$", fontsize='20')
plt.tick_params(axis='both', which='major', labelsize=12)
plt.show()